version: '3'
services:
  gatehub:
    container_name: Gatehub
    image: nineteensevenfour/gatehub
    ports:
      - 5443:443
      - 5080:80 
    #env_file:
    #  - docker-compose.dev.env
    volumes:
      - gatehub:/root/.aspnet/DataProtection-Keys
      - C:\storage\data\gate\:/data/

volumes:
  gatehub:
