name: Setup Node.JS
description: Release packages

inputs:
  npmRegistry:
    description: NPM Registry
    required: false
    default: https://npm.pkg.github.com ## https://registry.npmjs.org

  scope:
    description: Registry scope
    required: false
    default: nineteensevenfour

  gh_token:
    description: GH TOKEN
    required: true

runs:
  using: composite
  steps:
    - name: Semantic Release
      uses: MansaGroup/nrwl-nx-action@v3.1.0
      with:
        targets: semantic-release
        all: true
        parallel: 1
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
