name: Publish NPM
description: Publish NPM packages 
inputs:
  GH_TOKEN:
    description: GH TOKEN
    required: true
  NPM_TOKEN:
    description: NPM TOKEN
    required: true
runs:
  using: composite
  steps:
    - name: Release
      shell: bash
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
