name: Publish NPM
description: Publish NPM packages
runs:
  using: composite
  steps:
    - name: Release
      shell: bash
      run: npx semantic-release
      env:
      #env:
        #  GITHUB_TOKEN: ${{ github.token }}
        #  NPM_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
