name: Setup Dotnet
description: Setup Dotnet env (registry, authentication) and restore pacckages

inputs:
  version:
    description: Dotnet version
    required: false
    default: 6.0.x

  registry:
    description: NUGET Registry
    required: false
    default: https://nuget.pkg.github.com

  scope:
    description: NUGET Registry scope
    required: false
    default: nineteensevenfour

runs:
  using: composite
  steps:
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.version }}
        source-url: '${{ inputs.registry }}/${{ inputs.scope }}/index.json'
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      shell: bash
      run: dotnet restore
