name: Setup Node.JS
description: Setup Node.js env (registry, authentication) and restore pacckages

inputs:
  version:
    description: Node.js version
    required: false
    default: 16

  registry:
    description: NPM Registry
    required: false
    default: https://npm.pkg.github.com ## https://registry.npmjs.org

  scope:
    description: NPM Registry scope
    required: false
    default: nineteensevenfour

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ inputs.version }}
        ## This doesn't just set the registry url, but also sets
        ## the right configuration in .npmrc that reads NPM token
        ## from NPM_AUTH_TOKEN environment variable.
        ## It actually creates a .npmrc in a temporary folder
        ## and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: ${{ inputs.registry }}
        ## Defaults to the user or organization that owns the workflow file
        scope: '@${{ inputs.scope }}'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: npm ci
