name: Prepare
description: Prepare GIT

inputs:
  baseRef:
    description: GIT reference
    required: false
    default: main

runs:
  using: composite
  steps:
    ## Make sure we have all branches so that nx affected works.
    - name: Fetch other branches
      shell: bash
      run: git fetch --no-tags --prune --depth=5 origin ${{ inputs.baseRef }}

    - name: Setup git user to "NineteenSevenFour Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "NineteenSevenFour Bot"
