#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

## deactivated for apps due to netsdk 7 being broken and fils to load Codenalyzer
nx affected --target=lint --exclude NineteenSevenFour.Gatehub, NineteenSevenFour.Gatehub.Test
nx affected --target=format
nx affected --target=test

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
