#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

nx affected --target=lint
nx affected --target=format
nx affected --target=test

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
