name: Prepare GIT
description: Prepare GIT (default branch, bot user)

runs:
  using: composite
  steps:
    - name: Configure git
      shell: bash
      run: |
      git config user.email "-" && \
      git config user.name "NineteenSevenFour Bot" && \
      git config --global init.defaultBranch <name>

