name: Portal CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      # Make sure we have all branches so that nx affected works.
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: |
          npm ci

      - name: Check
        run: |
          npm run lint
          npm run format

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run build
