name: pr

on:
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha
      - '*.x' # maintenance releases branches
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest #self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        dotnet-version: [6.0.x]

    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/01-prepare
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ./.github/actions/02-setup-dotnet
        with:
          version: ${{ matrix.dotnet-version }} # uses the matrix defined above
          registry: https://nuget.pkg.github.com # optional / default value
          scope: nineteensevenfour # optional / default value

      - uses: ./.github/actions/03-setup-node
        with:
          version: ${{ matrix.node-version }} # uses the matrix defined above
          registry: https://npm.pkg.github.com # optional / default value
          scope: nineteensevenfour # optional / default value

      - uses: ./.github/actions/04-validate
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          coverage_files: ./coverage/apps/adcon/cobertura-coverage.xml,./coverage/apps/portal/cobertura-coverage.xml,./coverage/libs/sdk/cobertura-coverage.xml
          coverage_report_name: nineteensevenfour-gate

      - uses: ./.github/actions/05-build
