name: release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - uses: ../actions/setup/action.yml
        with:
          ref: ${{ github.head.ref }}
          node-version: ${{ matrix.node-version }}
      - uses: ../actions/build/action.yml
      - uses: ../actions/publish-npm/action.yml
